n = input('Digite um valor: ')
print('O tipo primitivo é ', type(n))
print('É número? ', n.isnumeric())
print('É alfabético numérico? ', n.isalnum())
print('É ? ', n.isascii())
print('É decimal? ', n.isdecimal())
print('É alfabético? ', n.isalpha())
print('É um dígito? ', n.isdigit())
print('É minúsculo? ', n.islower())
print('É maiúscula? ', n.isupper())
